global using Serilog;
global using Serilog.Events;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using System.Threading;
global using SerilogTimings;
global using System;
global using Global;